### ISSUE TITLE
Баг с руссификацией

### ISSUE THREAD

**Issue by gaydin** [livestreet/lsplugin-admin#45]
После настройки конфига кэширования в админке на memcached получается такая вещь:
![image](https://cloud.githubusercontent.com/assets/1359712/5412286/18654bb2-821c-11e4-86a4-778a5023192d.png)
php-fpm 5.6, nginx 1.6, memcached 1.4.21

**Comment by psnet** [comment]
Обновите движок + фреймворк + админку и проверьте ещё раз
