### ISSUE TITLE
Ошибка 

### ISSUE THREAD

**Issue by sgavka** [livestreet/lsplugin-admin#54]
На страницах плагина появляется следующие ошибки:
Warning: array_keys() expects parameter 1 to be array, null given in /home/servers/ls2.ga/application/plugins/admin/classes/actions/ActionAdmin.class.php on line 496

Warning: Invalid argument supplied for foreach() in /home/servers/ls2.ga/application/plugins/admin/classes/actions/ActionAdmin.class.php on line 496

https://github.com/livestreet/lsplugin-admin/blob/master/classes/actions/ActionAdmin.class.php#L495 собственно тут ошибка.

Config::Get(PluginAdmin_ModuleSettings::ROOT_CONFIG_GROUPS_KEY) выводит NULL.

Используется версия с гита (и LS и плагин).

**Comment by sgavka** [comment]
А вот эту ошибку показывает сам ЛС (на странице админки):
Ошибка соединения с каталогом: Operation timed out after 0 milliseconds with 0 out of 0 bytes received

**Comment by psnet** [comment]
По второй ошибке - ошибка регулярная?

**Comment by sgavka** [comment]
@psnet нет, она уже пропала.

**Comment by psnet** [comment]
@sgavka такое иногда бывает если каталог занят.

по поводу первого - права на все файлы одинаковые? все файлы закачаны?

**Comment by sgavka** [comment]
@psnet права на все файлы/папки 777. Вроде как всё закачалось (я клонировал всё с гита).

**Comment by psnet** [comment]
1. Перепроверьте все файлы ли закачаны.
2. Это чистая установка (ранее не использовали движок/аминку) или обновление альфы?

**Comment by sgavka** [comment]
2. Да чистая установка.

**Comment by sgavka** [comment]
Может ли быть как-то с этим всем связана ещё следующая проблема: не сохраняются изменения сделанные на странице Настройки плагина "Admin panel NEW".

**Comment by sgavka** [comment]
1. Залил заново админку — ошибка всё равно появляется.

**Comment by psnet** [comment]
Уже вижу, эта ошибка у всех, буду разбираться

**Comment by sgavka** [comment]
Кажется, конфиг из application/plugins/admin/config/root_config/config.php не подгружается.

А https://github.com/livestreet/lsplugin-admin/blob/master/classes/actions/ActionAdmin.class.php#L495 пофиксил так:
``foreach (array_keys((array)Config::Get(PluginAdmin_ModuleSettings::ROOT_CONFIG_GROUPS_KEY)) as $sKey) {
``

**Comment by sgavka** [comment]
Этот хук не запускается application/plugins/admin/classes/hooks/HookSettings.class.php

**Comment by psnet** [comment]
>Кажется, конфиг из application/plugins/admin/config/root_config/config.php не подгружается.

именно так

Баг будет исправлен, когда будут внесены правки в сам фреймворк https://github.com/livestreet/livestreet-framework/issues/114

**Comment by psnet** [comment]
Это ошибка сегодняшнего коммита в фреймворк, которая поломала загрузку хуков плагинов.
