### ISSUE TITLE
В админке не подключаются css и js плагинов

### ISSUE THREAD

**Issue by venticello** [livestreet/lsplugin-admin#57]

**Comment by mzhelskiy** [comment]
их нужно подключать отдельно через конфиг
``
$config['admin']['assets']['js']=array();
``

**Comment by venticello** [comment]
А как для пользователей это сделать автоматом, чтобы можно было по полной использовать админу для администрирования плагина? Или проще скрипты подключать прямо в шаблоне где используются?

**Comment by mzhelskiy** [comment]
не понял вопроса
этот конфиг нужно прописать в нужном плагине, а не в плагине админки

**Comment by venticello** [comment]
Стормозил зачит, попробую спасибо!

**Comment by psnet** [comment]
@venticello работает?

**Comment by venticello** [comment]
Да и стили тоже подключаются таким образом, сделал отдельные файлы для
админки. Так как некоторые функции js тянули компоненты, которые в админке
не подключены.

вторник, 28 апреля 2015 г. пользователь Serge Pustovit написал:
