### ISSUE TITLE
При посмотре админки на мобильном не видно меню

### ISSUE THREAD

**Issue by venticello** [livestreet/lsplugin-admin#59]
С мобильного не видно панель с меню, вернее есть полоска с которой как понимаю меню должно выпадать, но при тапе по ней ничего не происходит, и соответственно не попасть в другие разделы.

**Comment by psnet** [comment]
>но при тапе по ней ничего не происходит,

Там на данный момент не работает очень много ЖС кода (дропдауны, меню и т.п.) в связи с тем, что админка использует старые ксс классы фреймворка и жс-код, поэтому вполне возможно такое поведение.

Как будет более-менее сформирован стабильно фреймворк - будет адаптация админки к нему.
