### ISSUE TITLE
Отображение админки

### ISSUE THREAD

**Issue by sgavka** [livestreet/lsplugin-admin#60]
https://mrkr.io/21qTdkIsqo вот так отображается сейчас у меня админка. Это, конечно, больше к фронтенду, но всё таки нужно бы решить.
Только поставил LS2 и админку с github`a.

**Comment by psnet** [comment]
Фронтенд админки полурабочий в связи с тем, что были изменены стили и жс скрипты фреймворка, а админка к ним не адаптировалась с того момента и это будет выполнено после того как фреймворк выйдет в более стабильный релиз, поэтому пока интерфейс остается таким.

**Comment by sgavka** [comment]
Понятно, спасибо.
