### ISSUE TITLE
Кеширование

### ISSUE THREAD

**Issue by Xmk** [livestreet/lsplugin-admin#72]
Если при **выключенном** кешировании сменить шаблон или настройки сайта\плагинов - без сброса кеша изменения не отображаются.

**Comment by mzhelskiy** [comment]
Это как? Какое именно кеширование имеется ввиду?

**Comment by Xmk** [comment]
Щас в ручную поудаляю, скажу какое именно

**Comment by Xmk** [comment]
\application\tmp\system

**Comment by mzhelskiy** [comment]
не могу повторить
пробовал и при вкл кеше и выкл - работает

**Comment by Xmk** [comment]
сейчас обновлю все что можно и еще раз попробую

**Comment by Xmk** [comment]
в config.local.php добавил
$config['sys']['cache']['use'] = true;
и снова ловлю эту ошибку (через админку кеширование выключено)

**Comment by Xmk** [comment]
перезапись конфига где-то косячит может? от этого и соседний тикет (per_page) - в базу пишется, а из базы не переписывает

**Comment by mzhelskiy** [comment]
В том тикете проблема была в том, что сейчас конфиг перезаписывается из базы только тогда, когда эти параметры конфига используются в интерфейсе настроек админки/плагина.
Ты правил дефолтные схемы для конфига?

**Comment by Xmk** [comment]
нет, локалку запустил, скачал только что отсюда cms, fm и админку. установил

**Comment by Xmk** [comment]
постраничность заработала, но точно так же - пока включен кеш через локальный конфиг - без его сброса изменения не отображаются

**Comment by mzhelskiy** [comment]
Кстати, не уловил - в первом посте ты писал, что ошибка при **выключенном** кеше. Далее что при `$config['sys']['cache']['use'] = true;`
Какое окружение у сервера?

**Comment by Xmk** [comment]
кеш выключен настройками админки, что в конфиге выставлено true выяснилось позже (но по статистике кешируется только 1 какой-то запрос).
окружение local

**Comment by mzhelskiy** [comment]
под окружением имел ввиду версию php и прочее

**Comment by Xmk** [comment]
win10 apache-php-7-x64+Nginx-1.10 + php7-x64
аналогично работает на рабочем сервере Debian apache+nginx php5.6

**Comment by mzhelskiy** [comment]
воспроизвел, буду разбираться

**Comment by mzhelskiy** [comment]
Проблема в том, что запрос к таблице с конфигом кешируется с учетом опций из config.php, которые перезаписываются уже после получения данных из таблицы. Варианта два - либо не кешировать запрос к storage, либо убрать из админки возможность настройки кеша, оставить только в файле.

**Comment by Xmk** [comment]
Понял.
На мой взгляд логичней второе - управлять настройкой кеширование должен только владелец ресурса, а не любой администратор.
